name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd "echo 'SELECT 1 FROM DUAL;' | sqlplus system/oracle@//localhost:1521/XEPDB1"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      env:
        DJANGO_SETTINGS_MODULE: crud_project.settings
        DATABASE_HOST: localhost
        DATABASE_PORT: 1521
        DATABASE_USER: system
        DATABASE_PASSWORD: oracle
        DATABASE_NAME: XEPDB1
      run: |
        python manage.py migrate
        pytest -v
