name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      env:
        DJANGO_SETTINGS_MODULE: crud_project.settings
        USE_SQLITE: "true"  # 👈 si lo usás en tu settings para alternar
      run: |
        python manage.py migrate
        pytest productos/tests/test_views.py -v
